### ISSUE TITLE
As a starting point - should we discuss what we can learn from RDMKit

### ISSUE THREAD

**Issue by shoaibsufi** [EVERSE-ResearchSoftware/RSQKit#1]
Should we discuss what we can learn and maybe lift from the RDMKit (https://rdmkit.elixir-europe.org/) for the RSQKit - 

- The contribution model might be something we could take and adapt - https://rdmkit.elixir-europe.org/how_to_contribute
- We might consider using the technical platform which is jekyll & markdown based or something similar e.g. Sphinx https://rdmkit.elixir-europe.org/working_with_git

**Comment by dgarijo** [comment]
I agree, especially on the open contribution model :)
I had Sphynx in mind, possibly through readthedocs.

**Comment by egpbos** [comment]
We have started using the https://elixir-belgium.github.io/elixir-toolkit-theme/ which is the basis of the RDMKit and other sites.

Indeed the contribution model looks good! Hopefully we can discuss it this week.

**Comment by dgarijo** [comment]
Since we are basing RSQKit on the template and structure of RDMKit, I am closing this issue
