### ISSUE TITLE
The training page on RSQKit seems to be full of html can this be fixed

### ISSUE THREAD

**Issue by shoaibsufi** [EVERSE-ResearchSoftware/RSQKit#114]
If you go to https://everse.software/RSQKit/all_training_resources

You don't see a blank page - you see lots of html:

![Screenshot 2024-12-03 at 12 00 24](https://github.com/user-attachments/assets/76e84c93-803c-4772-95ad-f78e24ecf4ff)

Can this be fixed - so it can be brief but tidy (i.e. no block of html)

**Comment by dgarijo** [comment]
ugh, this is not cool at all! We need to have a look

**Comment by anenadic** [comment]
Duplicates #93.
