### ISSUE TITLE
Create quality_indicators.yml data file

### ISSUE THREAD

**Issue by anenadic** [EVERSE-ResearchSoftware/RSQKit#125]
- [x] Use the currently agreed schema. Update in the future as needed.
- [x] Populate with a few indicators to be used as tags in pages

**Comment by dgarijo** [comment]
Example: https://github.com/EVERSE-ResearchSoftware/RSQuality_indicators/blob/main/template.yaml (not yet finished)

**Comment by anenadic** [comment]
Please ad @shoaibsufi as a reviewer when the PR is ready for review.

**Comment by dgarijo** [comment]
Will do. Thanks! Will happen this week.

**Comment by dgarijo** [comment]
Done in #174

**Comment by anenadic** [comment]
Closed via #174
