### ISSUE TITLE
Fix tables listing all tools/resources/training

### ISSUE THREAD

**Issue by anenadic** [EVERSE-ResearchSoftware/RSQKit#130]
These tables show data fields we do not have in our data (e.g. registry, etc.). This needs updating.

<img width="1463" alt="image" src="https://github.com/user-attachments/assets/f15cac1e-a7e3-4cf4-81f5-2d2179819642">

**Comment by dgarijo** [comment]
We do have them, if we add them in the correct places. We plan to link to tess, so I think it's an issue of updating the tool list. See  "Docker" for an example where it is properly depicted

**Comment by anenadic** [comment]
Once we settle on the data schema for resources, if we decide we do not need the registry fields there, or to have a link to TeSS is a differenct way, we need to revisit this table - this issues is a reminder to do that.

**Comment by anenadic** [comment]
Will be addressed as part of #90 - closing.
