### ISSUE TITLE
Add own website icon for RSQkit

### ISSUE THREAD

**Issue by juckel** [EVERSE-ResearchSoftware/RSQKit#136]
RSQkit currently shows the "ETT" web icon: 
![image](https://github.com/user-attachments/assets/86f8bb58-5301-42e0-b9df-23bd4ae5e029)

Maybe substitute this with the same used for the main https://everse.software page or even create an own RSQkit icon?

**Comment by graeme-a-stewart** [comment]
FYI, the main site icons are here: https://github.com/EVERSE-ResearchSoftware/EVERSE-ResearchSoftware.github.io/tree/main/static

**Comment by anenadic** [comment]
Thanks guys! There is definitely work to be done on the "look at feel" of the RQSKit website - I am going to create an issue for that (a bigger issue around branding and the creation of graphics). The favicon should be easy enough to fix though.

**Comment by dgarijo** [comment]
Haha I opened an issue on the main everse page about the same, now it comes back to the RSQkit. Call it karma :D

**Comment by anenadic** [comment]
See the PR #138 @dgarijo for the fix.
