### ISSUE TITLE
Implement licensing decision on RSQKit

### ISSUE THREAD

**Issue by shoaibsufi** [EVERSE-ResearchSoftware/RSQKit#153]
implement licensing decision on RSQKit
- Based on consortium agreement: 
   - Content should be CC-BY 
   - Metadata should be CC-0
   - New code that we add - RDMkit uses MIT

Copyright: “Members of the EVERSE consortium and external contributors” - in the README and the website

**Comment by jmaassen** [comment]
In progress in branch 153-licensing

**Comment by jmaassen** [comment]
@anenadic @shoaibsufi Should we change the footer to something similar to what [RDMkit](https://rdmkit.elixir-europe.org/) is using?
