### ISSUE TITLE
Remove "Tools and resources" section from your_task template

### ISSUE THREAD

**Issue by anenadic** [EVERSE-ResearchSoftware/RSQKit#161]
There is "Related tools and resoruces" added automatically to the layout so there is duplication.

**Comment by dgarijo** [comment]
I think we need to move the contents of "Tools and Resources" to "Tools and resources on this page" (but that one seems to be automatically created)

**Comment by anenadic** [comment]
Once we tag pages properly, the "Tools and resources on this page"  will be populated automatically. We can do something similar for "Training on this page" or "Indicators on this page", or something similar we may find useful. 

Duplicate of #140.
