### ISSUE TITLE
Change science clusters to science domains

### ISSUE THREAD

**Issue by dgarijo** [EVERSE-ResearchSoftware/RSQKit#42]
This was considered more appropriate

**Comment by anenadic** [comment]
Something like

Your Science domain or community:
- Physics and astronomy
   - PANOSC, ESCAPE
-Biomedical sciences
- Social sciences & hummanities
   - SSHOC

**Comment by dgarijo** [comment]
But if I understood correctly, we don't want to "label" clusters so far no? So for now we'll have:
- Science domains:
  - Science clusters
    - SSHOC
    - PANOSC
