### ISSUE TITLE
Search includes template

### ISSUE THREAD

**Issue by dgarijo** [EVERSE-ResearchSoftware/RSQKit#87]
Even though the template has `search_exclude` to true.
@anenadic do you know why this could be?

**Comment by dgarijo** [comment]
See the following task in https://everse.software/RSQKit/your_tasks:
![image](https://github.com/user-attachments/assets/eca8667f-7e3a-47b6-a201-85287219d144)

**Comment by anenadic** [comment]
Fixed via #139.

**Comment by bedroesb** [comment]
https://github.com/EVERSE-ResearchSoftware/RSQKit/blob/main/pages/your_tasks/TEMPLATE_your_tasks.md?plain=1#L3 still has the placeholder, not just `true`

**Comment by anenadic** [comment]
> https://github.com/EVERSE-ResearchSoftware/RSQKit/blob/main/pages/your_tasks/TEMPLATE_your_tasks.md?plain=1#L3 still has the placeholder, not just `true`

I am sorry not sure I am following - is it the HTML style comment that is causing the problem and needs to be removed @bedroesb? 

I was wondering if the HTML style comment in the field is causing the issue and wanted to remove it (but thought that because people are expected to copy this file - we are not meant to remove the comment that tells them what to do).

**Comment by bedroesb** [comment]
Inside the yaml, you actually have to use yaml style comments, if you don't want them to be parsed.

**Comment by bedroesb** [comment]
For example:

```
search_exclude: true #leave as “true” until the page is complete and ready to be made public
```

**Comment by anenadic** [comment]
> Inside the yaml, you actually have to use yaml style comments, if you don't want them to be parsed.

Exactly! I thought we copied this template from one the RDMkit templates but have now realised it must have been one of us that has created this template with the wrong style comments which are causing issues. Thank you!
