### ISSUE TITLE
RSQKit training resources is broken

### ISSUE THREAD

**Issue by dgarijo** [EVERSE-ResearchSoftware/RSQKit#93]
See https://everse.software/RSQKit/all_training_resources
@anenadic any pointers?

**Comment by anenadic** [comment]
This is the commit that touched the [all_training_resources](https://everse.software/RSQKit/all_training_resources) file: https://github.com/EVERSE-ResearchSoftware/RSQKit/commit/492c8f162fd4769301db85bc0421e3eccd8ac378 👀 😆.

I am creating a PR with a fix.

**Comment by dgarijo** [comment]
Thanks!

**Comment by anenadic** [comment]
Here is the PR: https://github.com/EVERSE-ResearchSoftware/RSQKit/pull/123

**Comment by dgarijo** [comment]
Thanks!
